import os

from agents.base import BaseAgent
from config import PROJECT_DIRECTORY
from utils import list_files_recursively

PROMPT = """
When writing the code:
- All files you may need already exist and are available to you.
- All dependencies are already installed.
- When writing the code, output the whole file. Your output will replace the whole content of the file.

The current task is: {task}

Codebase structure in annotations of other files in this project:
{annotations}

Files in this project:
{files}

Content of current file:
{current_file_content}

Note: Always use 'encoding='utf-8'' when opening files with open().
Based on the task and objective, write the appropriate code to achieve the task. Make sure the code is relevant to the task and objective, and follows best practices. Return just the code as a plain text output. Use identation and line breaks in the in the code.
"""


def read_file(file_path):
    # If the file does not exist, return an empty string
    if not os.path.exists(file_path):
        return "[file does not exist]"

    with open(file_path, "r", encoding="utf-8") as f:
        return f.read()


class DeveloperAgent(BaseAgent):
    system_prompt = """You are a skilled python programmer responsible for writing code to accomplish a given task. Your goal is to analyze the provided major objective of the project and a single task from the JSON checklist generated by the previous agent, and write the necessary code to complete the task."""
    prompt = PROMPT
    extract_code = True
    temperature = 0.2

    def __init__(self, task):
        self.task = task

        files_in_project = list_files_recursively(PROJECT_DIRECTORY)

        super().__init__(
            task=task,
            annotations="[skip]",
            files=files_in_project,
            current_file_content=read_file(task["file"]),
        )

    def write_code(self, code):
        path = self.prompt_kwargs["task"]["file"]

        # If the file already exists, delete it
        if os.path.exists(path):
            os.remove(path)

        # If the path does not exist, create the directory strtucture
        os.makedirs(os.path.dirname(path), exist_ok=True)

        # Write the code to the file
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
